### ISSUE TITLE
Get Custom Fields

### ISSUE THREAD

**Issue by hayrullahmete** [code4me/4me-sdk-graphql-dotnet#13]
I am not sure but I think SDK doesn't get org custom values. By using same request body, Postman returns that values but I couldn't get these values via SDK. Maybe it's related to my API configuration but it would be good to check.

PS: Custom fields of organization are created at directory side.

![Screenshot_Code](https://github.com/user-attachments/assets/73fa8365-399f-4f4d-8b53-953a5b5504a9)

![Screenshot_Code_Response](https://github.com/user-attachments/assets/196738fe-769e-4731-a413-7d10a435be36)

![Screenshot_Postman](https://github.com/user-attachments/assets/b323d76b-9715-4c63-845b-924bae60c7e7)

**Comment by klaasvandeweerdt** [comment]
@hayrullahmete, I will look at it, what is the expected data type for that field?

**Comment by hayrullahmete** [comment]
Hi @klaasvandeweerdt ,
Data types vary depending on the data we use. It can be an id that refers to another object (_like person id or custom collection element id_), it can be any string value, or it can be an array which is included any type. It can be all data types used by 4me.

**Comment by klaasvandeweerdt** [comment]
@hayrullahmete , I'm unable to reproduce this. When I run the following code, it output my custom field.
```csharp
var organizations = await client.Get(new OrganizationQuery().Select(OrganizationField.ID, OrganizationField.Name, OrganizationField.CustomFields));
foreach (var customField in organizations.Last().CustomFields)
{
    Console.WriteLine(customField.ID);
    Console.WriteLine(customField.Value);
}
```
I had a similar issue when I was implementing the integration through PowerShell, the `.ToString()` return a empty value where `.Values<string>()` did return the values.

**Comment by hayrullahmete** [comment]
@klaasvandeweerdt I think there is weird situation by using Web API about JSON Converter.  When I debugging, I can see correct data in CustomFields. But at the end, because of IActionResult and return Ok, the data corrupts. I tried to use custom convertion but I didn't implement correctly. Have you ever tried this SDK at web API?

![image](https://github.com/user-attachments/assets/c3b297ed-5bad-4038-8662-23707e93a239)

![image](https://github.com/user-attachments/assets/ece8ec3f-0ab9-4004-86e1-1c99e88434d4)

![image](https://github.com/user-attachments/assets/02263200-328c-449e-90a1-fc5c0a7bf5f9)

**Comment by klaasvandeweerdt** [comment]
@hayrullahmete, not sure why this fails, my guess would be the serialization. The SDK uses Newtonsoft Json.NET. You could try it that way, `Services.AddControllers().AddNewtonsoftJson(options =>{ ... });`, or implement your own custom convertor.
```csharp
public class JTokenConverter : JsonConverter<JToken>
{
    public override JToken Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var json = reader.GetString();
        return JToken.Parse(json);
    }

    public override void Write(Utf8JsonWriter writer, JToken value, JsonSerializerOptions options)
    {
        writer.WriteRawValue(value.ToString());
    }
}
```
```csharp
Services.AddControllers().AddJsonOptions(options => { options.JsonSerializerOptions.Converters.Add(new JTokenConverter()); });
```

**Comment by hayrullahmete** [comment]
Hi @klaasvandeweerdt ,
I gave up using Web API because even if I used custom serialization, I could not make a correct conversion. So I developed console app instead of Web API. I close this issue now, thanks for your support.
