### ISSUE TITLE
Get Object Self ID

### ISSUE THREAD

**Issue by hayrullahmete** [code4me/4me-sdk-graphql-dotnet#14]
Hi,
It's not issue, I think it's suggestion. I want to get id of team, service, service instance or something like, (_not "N1123n1asf..." id, I need id at url_). I checked the properties of return object but I couldn't see. I want to get this, because I use in-memory caching in my middleware API and these values is used to transfer or update etc.

![image](https://github.com/user-attachments/assets/69d50783-a30e-4c08-a990-8183a0e7ab9f)

![image](https://github.com/user-attachments/assets/1570e1be-a83a-4e18-96d0-4d26b29b1ce9)

**Comment by klaasvandeweerdt** [comment]
@hayrullahmete,
You should be able to get the ID via the `GetIdentifier()` method. Example: `team.GetIdentifier()`
If it is an object without `ID` it will return 0.
I hope this helps.

**Comment by hayrullahmete** [comment]
Oh, this answer is exactly what I was looking for. Thank you @klaasvandeweerdt  

![image](https://github.com/user-attachments/assets/3fa40696-9bb3-47e0-a364-129bcd9b8cd6)
