### ISSUE TITLE
Pagination of huge dataset

### ISSUE THREAD

**Issue by hayrullahmete** [code4me/4me-sdk-graphql-dotnet#16]
Hi,
Actuall I didn't understand about pagination. I have 1000+ records but if I used ItemsPerRequest, I can't get all records (_1250 service instances_). I also looked up the new version of SDK (_[Xurrent.GraphQL](https://www.nuget.org/packages/Xurrent.GraphQL/)_) but I couldn't figure this out. You said "_it will automatically retrieve the next 100 items without the need to write a new query_" at [pagination link](https://github.com/code4me/4me-sdk-graphql-dotnet?tab=readme-ov-file#pagination)

These codes return maximum 1000 records. How can I get all the data (1000+)?

```

ServiceInstanceQuery objectQuery = new ServiceInstanceQuery()
    .ItemsPerRequest(1000)
    .Select(ServiceInstanceField.ID, ServiceInstanceField.Name, ServiceInstanceField.Status)
    .SelectService(new ServiceQuery().Select(ServiceField.ID, ServiceField.Name, ServiceField.Disabled));
```
or

```
IQuery query = Query.ServiceInstance
    .Select(ServiceInstanceField.ID, ServiceInstanceField.Name, ServiceInstanceField.Status, ServiceInstanceField.Service)
    .ItemsPerRequest(1000)
    .SelectService(new ServiceQuery().Select(ServiceField.ID, ServiceField.Name, ServiceField.Disabled));
```

**Comment by klaasvandeweerdt** [comment]
@hayrullahmete, the client contains two properties that control the total number of returned records, see the [Client](https://github.com/code4me/4me-sdk-graphql-dotnet?tab=readme-ov-file#client) in the documentation.
- `DefaultItemsPerRequest` property sets the number of items per connection request, with a default and maximum value of 100.
- `MaximumRecursiveRequests` property controls the number of recursive requests that the client can make when pagination occurs in the top level query. The default value is 10.

Those two limit it to 1000, 100 item per request and maximum 10 recursive requests. Change the `MaximumRecursiveRequests` and it will load more pages.

`DefaultItemsPerRequest` can be set via the query as well as it also allows you to control pagination on non-root levels. It can never be higher than 100, if you set 1000 as in your example it will still use 100.

A quick example of a client initialization with the `MaximumRecursiveRequests` set to 100, which means 100 item per page pages x 100 recursive requests = maximum 10.000 items.
```csharp
XurrentClient client = new(tokens, "wdc", EnvironmentType.Demo, EnvironmentRegion.EU)
{
    MaximumRecursiveRequests = 100
};
```

**Comment by hayrullahmete** [comment]
I exactly understood now. Thank you so much for your support @klaasvandeweerdt
