### ISSUE TITLE
Examples obsolete

### ISSUE THREAD

**Issue by hczlapinski** [code4me/4me-sdk-graphql-dotnet#17]
Some examples of how to upload attachments are obsolete. Could you (or are you planning to) update the examples here?

**Comment by klaasvandeweerdt** [comment]
@hczlapinski, thank you for pointing that out! The examples have been updated. When executing a mutation, you need to specify the response query explicitly.

The [Xurrent.GraphQL NuGet package](https://www.nuget.org/packages/Xurrent.GraphQL) is now available and is set to replace the `Sdk4me.GraphQL` package in the future.
