### ISSUE TITLE
Not able to add an address with label to new organization

### ISSUE THREAD

**Issue by HeinPauwelyn** [code4me/4me-sdk-graphql-dotnet#18]
When I want to create a new organization with the Sdk4me.GraphQL version 1.4.3, I got next error:

> Label is invalid

Below my code:

```csharp
using Sdk4me.GraphQL;

Sdk4meClient client = new(
    new AuthenticationToken(
        "<enter id here>",
        "<enter key here>"
    ),
    "<enter account here>",
    EnvironmentType.Quality,
    EnvironmentRegion.EU
);

OrganizationCreatePayload payload = await client.Mutation(
    new OrganizationCreateInput()
    {
        Name = "Test Organization",
        NewAddresses = [
            new AddressInput() {
                Street = "Random address 1997",
                City = "Town",
                Zip = "80000",
                Label = AddressLabel.Home,
                Integration = true,
            }
        ]
    },
    new OrganizationQuery().Select(OrganizationField.ID),
    throwOnError: false);

if (payload.Organization is not null)
{
    Console.ForegroundColor = ConsoleColor.Green;
    Console.WriteLine(payload.Organization.ID);
}
else
{
    Console.ForegroundColor = ConsoleColor.Red;
    Console.WriteLine(payload.Errors[0].Message);
}

Console.ReadLine();
```

Could this bug be fixed?

**Comment by klaasvandeweerdt** [comment]
@HeinPauwelyn,
While all addresses labels are defined in a single enum only `street`, `mailing` and `billing` can be used for organizations. They are listed on [Organizations - Addresses API](https://developer.xurrent.com/v1/organizations/addresses/#fields).

The `Xurrent.GraphQL` NuGet package is now available and is intended to replace the `Sdk4me.GraphQL` package in the future. The code repository for this package is accessible on [GitHub](https://github.com/xurrent/graphql-dotnet).

**Comment by HeinPauwelyn** [comment]
Oh now I see, the enum is reused for persons too. Thanks for the replay.
