### ISSUE TITLE
Can not get serviceInstance from serviceLevelAgreements from organization.

### ISSUE THREAD

**Issue by HeinPauwelyn** [code4me/4me-sdk-graphql-dotnet#2]
# Situation

From an organization I try to get the SLAs with the service instance and the service. In GraphQL is this the body:

```graphql 
{
    organizations (
        first: 1
        filter: { 
            id: { values: [ "<enter id here>" ]}
        }
    ) {
        nodes {
            id
            name
            serviceLevelAgreements(first: 100) {
                nodes {
                    id
                    name
                    serviceInstance {
                        id
                        name
                        service {
                            id
                            name
                        }
                    }
                }
                totalCount
            }
        }
        totalCount
    }
}
```

# Solution 1

If I want to use the defined method of the `OrganizationQuery`, I see that `SelectServiceInstance` and `SelectService` gives a compilation error.

```csharp
new OrganizationQuery()
    .Filter(OrganizationField.ID, FilterOperator.Equals, "<enter id here>")
    .SelectServiceLevelAgreements(new ServiceLevelAgreementQuery()
        .Select("id")
        .SelectServiceInstance(new ServiceInstanceQuery()
         ~~~~~~~~~~~~~~~~~~~~~
            .SelectService(new ServiceQuery()
             ~~~~~~~~~~~~~
                .Select("id")
            )
        )
        .SelectCustomerRepresentatives(new PersonQuery()
            .Select("id")
        )
    );
```

> - `ServiceLevelAgreementQuery` does not contain a definition for 'SelectServiceInstance' and no accessible extension method `SelectServiceInstance` accepting a first argument of type `ServiceLevelAgreementQuery` could be found (are you missing a using directive or an assembly reference?)
>
> - `ServiceInstanceQuery` does not contain a definition for `SelectService` and no accessible extension method `SelectService` accepting a first argument of type `ServiceInstanceQuery` could be found (are you missing a using directive or an assembly reference?)

# Solution 2

When I want to fix this into next code:

```csharp
new OrganizationQuery()
    .Filter(OrganizationField.ID, FilterOperator.Equals, "<enter id here>")
    .SelectServiceLevelAgreements(new ServiceLevelAgreementQuery()
        .Select("id", "serviceInstance { id service { id } }")
        .SelectCustomerRepresentatives(new PersonQuery()
            .Select("id")
        )
    );
```

I got next runtime error

> **`Sdk4me.GraphQL.Sdk4meInvalidFieldNameException`:** `serviceInstance { id service { id } }`

# Question

How could I become the GraphQL query that is shown above using this library?

# Extra information

* **Library verion:** 1.0.5
* **.NET version:** 6.0

**Comment by HeinPauwelyn** [comment]
# Update: solution 3

When using `SelectAll` method

```csharp
new OrganizationQuery()
    .Filter(OrganizationField.ID, FilterOperator.Equals, "<enter id here>")
    .SelectAll();
```

I got this exception:

> **`Sdk4me.GraphQL.Sdk4meException`:** The query exceeds the maximum allowed depth level connections value. The maximum value is set to 2, and the query contains 3 depth level connections.

**Comment by klaasvandeweerdt** [comment]
@HeinPauwelyn
Thanks again for the clear explanation and summary.

The select methods are for connections and the service instance is not a connection but a property.
It is currently not possible to select the properties of a property like you can with connections. It uses a set of default-selected properties and child properties. 

### Solution for the current problem
```csharp
OrganizationQuery query = new OrganizationQuery()
    .SelectServiceLevelAgreements(new ServiceLevelAgreementQuery()
        .Select("id", "serviceInstance")
        .SelectCustomerRepresentatives(new PersonQuery()
            .Select("id")
        )
    );
DataList<Organization> organizations = client.Get(query).Result;
```
This example should work for you. The `serviceInstance` includes `id`, `name`, and `service` by default, and the `service` includes `id` and `name` by default. I tested it and it returns all properties you used in your example query.

### Solution 3
`SelectAll()` will query all properties (not connections), and if those properties contain another set of properties you exceed the default query depth connection value. You have to explicitly set the maximum depth level, the default value is 2 and can be changed to a maximum of 13.
```csharp
client.MaximumQueryDepthLevelConnections = 3;
```
The `MaximumQueryDepthLevelConnections` comes with the following warning
```
Warning: changing this to a higher value can impact performance significantly because of the built-in pagination handling. The default value is 2.
```
### Conclusion
Nevertheless, I have to figure out how to make those properties selectable as well. Something like
```csharp
OrganizationQuery query = new OrganizationQuery()
    .SelectServiceLevelAgreements(new ServiceLevelAgreementQuery()
        .Select(new ServiceInstanceQuery() {"id", "name"})
    );
```

I will create a separate enhancement to make properties selectable.
This will take some time to do this properly.

**Comment by klaasvandeweerdt** [comment]
@HeinPauwelyn,
[Version 1.0.6](https://github.com/code4me/4me-sdk-graphql-dotnet/releases/tag/1.0.6) is available and you can now select fields of non-connection objects.
```csharp
OrganizationQuery query = new OrganizationQuery()
    .SelectServiceLevelAgreements(new ServiceLevelAgreementQuery()
        .SelectServiceInstance(new ServiceInstanceQuery()
            .Select(ServiceInstanceField.ID, ServiceInstanceField.Name))
        .SelectAccount(new AccountQuery()
            .Select(AccountField.Name, AccountField.Organization)));
```
