### ISSUE TITLE
Support file streams for attachments

### ISSUE THREAD

**Issue by Gustav16** [code4me/4me-sdk-graphql-dotnet#3]
Currently the SDK only supports direct local file references; files by name. It would be really nice if you could read a file from wherever you want and upload it to 4me, so thats why we need to support file streams.

**Comment by klaasvandeweerdt** [comment]
@Gustav16, I already did some tests to support streaming. The code is in the latest commit, and I will release a new NuGet this evening. One important thing is that the stream should support seeking as it needs to determine the file size during upload. 
For example, the `HttpClient.GetStreamAsync()` will not work, and `HttpResponseMessage.Content.ReadAsStreamAsync()` does work.
```csharp
using (HttpResponseMessage responseMessage = await httpClient.GetAsync("https://example.com/file.pdf"))
{
	using (Stream stream = await responseMessage.Content.ReadAsStreamAsync())
	{
		AttachmentUploadResponse response = await client.UploadAttachment(stream, "file.pdf", "application/pdf");
	}
}
```

**Comment by klaasvandeweerdt** [comment]
@Gustav16, NuGet 1.0.7 is published. You can now use a stream instead of files by name.
